spring:
  datasource:
    url: jdbc:mysql://52.79.111.170:3306/bankapi?allowPublicKeyRetrieval=true&useSSL=false
    username: springuser
    password: Goorm123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  tracing:
    enabled: true
  otlp:
    metrics:
      export:
        enabled: false
    logs:
      export:
        enabled: true
    endpoint: http://otel-collector:4318  # 4317에서 4318로 변경
    protocol: http/protobuf  # grpc에서 http/protobuf로 변경

otel:
  service:
    name: bankapi-service

logging:
  level:
    root: INFO
    com.eouil.bank.bankapi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
