spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3           # 최소 유휴 커넥션 수
      maximum-pool-size: 10     # 최대 커넥션 수 (DB 성능에 따라 조절)
      idle-timeout: 30000       # 유휴 상태 유지 시간 (30초)
      max-lifetime: 600000      # 커넥션 최대 생존 시간 (10분)
      connection-timeout: 30000 # 커넥션 획득 대기 시간 (30초)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
