  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  exporters:
    awsxray:
      region: ap-northeast-2
    awscloudwatchlogs:
      log_group_name: "/otel/bankapi"
      log_stream_name: "otel-log-stream"
      region: ap-northeast-2
    debug:
      verbosity: detailed

  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [debug, awsxray]
      logs:
        receivers: [otlp]
        exporters: [debug, awscloudwatchlogs]
